---
# tasks file for awsrole
- name: public-compute-instance
  ec2:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        wait: "{{ wait }}"
        count: "{{ count }}"
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: "{{ assign_ip }}"
        region: "{{ region }}"
        state: "{{ state }}"
        group_id: "{{ security_group }}"
        instance_tags:
          name: "{{ tag_name }}"
  register: ec2
